#!/bin/bash

usage() {
    echo "$0 - a tool to select random words from a source, to generate a strong passphrase"
    echo ""
    echo "Usage:"
    echo "$0 /path/to/source/text [selection_count]"
    echo "  /path/to/source/text - mandatory filepath to source text file"
    echo "  selection_count - optional, number of random words to select from source, defaults to 7"
}

main() {
    source=$1
    select_count=$2

    if [ -z "$source" ] || [ "$source" == "-h" ] || [ "$source" == "--help" ]; then
        usage
        exit 1
    fi

    re='^[0-9]+$'
    if ! [[ "$select_count" =~ $re ]] ; then
        select_count=7
    fi

    wordcount=$(cat $source | tr -cs A-Za-z '\n' | tr A-Z a-z | sort | uniq | wc -l)

    if [ $wordcount -lt 7776 ]; then
        (>&2 echo "Warning: Only $wordcount < 7776 unique words")
    fi

    cat $source | tr -cs A-Za-z '\n' | tr A-Z a-z | sort | uniq | shuf --random-source=/dev/urandom -n $select_count | tr '\n' ' '
}
main $@

